#code that tells Google App Engine how to send this code a web browser.
application: udacity4-1135
version: 1
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /css
  static_dir: css


- url: /.*
  script: project4.app

# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
